ETH_BUCKET = "coherent-ethereum-raw-parquet"

BLOCKS_TABLE_NAME="blocks"
TRANSACTIONS_TABLE_NAME="transactions"
TRACES_TABLE_NAME="traces"
LOGS_TABLE_NAME="logs"


BLOCKS="blocks"
TRANSACTIONS="transactions"
TRACES="traces"
LOGS="logs"

CONTRACTS_TABLE_NAME="contracts"

SNOWFLAKE_ACCOUNT="EVOPRNX-LP24558"
SNOWFLAKE_USER="EUNSEOUL"
SNOWFLAKE_PASSWORD="Coherent1234!"
SNOWFLAKE_DATABASE="CONTRACTS"
SNOWFLAKE_SCHEMA="EVM"
SNOWFLAKE_WAREHOUSE="PC_DBT_WH"
SNOWFLAKE_ROLE="ACCOUNTADMIN"

BATCH_SIZE=100